// LICENSE_CODE ZON ISC
'use strict'; /*jslint node:true, browser:true*/
(function(){
var define;
var is_node_ff = typeof module=='object' && module.exports;
if (!is_node_ff)
    define = self.define;
else
    define = require('./require_node.js').define(module, '../');
define([], function(){
var E = {};

E.list = {
    AF: 'Afghanistan',
    AL: 'Albania',
    DZ: 'Algeria',
    AX: 'Aland Islands',
    AS: 'American Samoa',
    AD: 'Andorra',
    AO: 'Angola',
    AP: 'Asia/Pacific',
    AI: 'Anguilla',
    AQ: 'Antarctica',
    AG: 'Antigua And Barbuda',
    AR: 'Argentina',
    AM: 'Armenia',
    AW: 'Aruba',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbaijan',
    BS: 'Bahamas',
    BH: 'Bahrain',
    JE: 'Bailiwick of Jersey',
    BD: 'Bangladesh',
    BB: 'Barbados',
    BY: 'Belarus',
    BE: 'Belgium',
    BZ: 'Belize',
    BJ: 'Benin',
    BM: 'Bermuda',
    BT: 'Bhutan',
    BO: 'Bolivia',
    BQ: 'Bonaire, Sint Eustatius and Saba',
    BA: 'Bosnia And Herzegovina',
    BW: 'Botswana',
    BV: 'Bouvet Island',
    BR: 'Brazil',
    IO: 'British Indian Ocean Territory',
    BN: 'Brunei',
    BG: 'Bulgaria',
    BF: 'Burkina Faso',
    BI: 'Burundi',
    KH: 'Cambodia',
    CM: 'Cameroon',
    CA: 'Canada',
    CV: 'Cape Verde',
    KY: 'Cayman Islands',
    CF: 'Central African Republic',
    TD: 'Chad',
    CL: 'Chile',
    CN: 'China',
    CX: 'Christmas Island',
    CC: 'Cocos (Keeling) Islands',
    CO: 'Colombia',
    KM: 'Comoros',
    CG: 'Congo',
    CK: 'Cook Islands',
    CR: 'Costa Rica',
    CI: "Cote D'Ivorie (Ivory Coast)",
    HR: 'Croatia (Hrvatska)',
    CU: 'Cuba',
    CW: 'Curacao',
    CY: 'Cyprus',
    CZ: 'Czech Republic',
    CD: 'Democratic Republic Of Congo (Zaire)',
    DK: 'Denmark',
    DJ: 'Djibouti',
    DM: 'Dominica',
    DO: 'Dominican Republic',
    TP: 'East Timor',
    EC: 'Ecuador',
    EG: 'Egypt',
    SV: 'El Salvador',
    GQ: 'Equatorial Guinea',
    ER: 'Eritrea',
    EU: 'European Union',
    EE: 'Estonia',
    ET: 'Ethiopia',
    FK: 'Falkland Islands (Malvinas)',
    FO: 'Faroe Islands',
    FJ: 'Fiji',
    FI: 'Finland',
    FR: 'France',
    FX: 'France, Metropolitan',
    GF: 'French Guinea',
    PF: 'French Polynesia',
    TF: 'French Southern Territories',
    GA: 'Gabon',
    GM: 'Gambia',
    GE: 'Georgia',
    DE: 'Germany',
    GH: 'Ghana',
    GI: 'Gibraltar',
    GB: 'Great Britain',
    GR: 'Greece',
    GL: 'Greenland',
    GD: 'Grenada',
    GP: 'Guadeloupe',
    GU: 'Guam',
    GT: 'Guatemala',
    GG: 'Guernsey',
    GN: 'Guinea',
    GW: 'Guinea-Bissau',
    GY: 'Guyana',
    HT: 'Haiti',
    HM: 'Heard And McDonald Islands',
    HN: 'Honduras',
    HK: 'Hong Kong',
    HU: 'Hungary',
    IS: 'Iceland',
    IN: 'India',
    ID: 'Indonesia',
    IR: 'Iran',
    IQ: 'Iraq',
    IE: 'Ireland',
    IM: 'Isle of Man',
    IL: 'Israel',
    IT: 'Italy',
    JM: 'Jamaica',
    JP: 'Japan',
    JO: 'Jordan',
    KZ: 'Kazakhstan',
    KE: 'Kenya',
    KI: 'Kiribati',
    KW: 'Kuwait',
    KG: 'Kyrgyzstan',
    LA: 'Laos',
    LV: 'Latvia',
    LB: 'Lebanon',
    LS: 'Lesotho',
    LR: 'Liberia',
    LY: 'Libya',
    LI: 'Liechtenstein',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    MO: 'Macau',
    MK: 'Macedonia',
    MG: 'Madagascar',
    MW: 'Malawi',
    MY: 'Malaysia',
    MV: 'Maldives',
    ML: 'Mali',
    MT: 'Malta',
    MH: 'Marshall Islands',
    MQ: 'Martinique',
    MR: 'Mauritania',
    MU: 'Mauritius',
    YT: 'Mayotte',
    MX: 'Mexico',
    FM: 'Micronesia',
    MD: 'Moldova',
    MC: 'Monaco',
    MN: 'Mongolia',
    ME: 'Montenegro',
    MS: 'Montserrat',
    MA: 'Morocco',
    MZ: 'Mozambique',
    MM: 'Myanmar (Burma)',
    NA: 'Namibia',
    NR: 'Nauru',
    NP: 'Nepal',
    NL: 'Netherlands',
    AN: 'Netherlands Antilles',
    NC: 'New Caledonia',
    NZ: 'New Zealand',
    NI: 'Nicaragua',
    NE: 'Niger',
    NG: 'Nigeria',
    NU: 'Niue',
    NF: 'Norfolk Island',
    KP: 'North Korea',
    MP: 'Northern Mariana Islands',
    NO: 'Norway',
    OM: 'Oman',
    PK: 'Pakistan',
    PW: 'Palau',
    PS: 'Palestine',
    PA: 'Panama',
    PG: 'Papua New Guinea',
    PY: 'Paraguay',
    PE: 'Peru',
    PH: 'Philippines',
    PN: 'Pitcairn',
    PL: 'Poland',
    PT: 'Portugal',
    PR: 'Puerto Rico',
    QA: 'Qatar',
    RE: 'Reunion',
    RO: 'Romania',
    RU: 'Russia',
    RW: 'Rwanda',
    BL: 'Saint Barthelemy',
    SH: 'Saint Helena',
    KN: 'Saint Kitts And Nevis',
    LC: 'Saint Lucia',
    MF: 'Saint Martin',
    PM: 'Saint Pierre And Miquelon',
    VC: 'Saint Vincent And The Grenadines',
    SM: 'San Marino',
    SX: 'Sint Maarten',
    ST: 'Sao Tome And Principe',
    SA: 'Saudi Arabia',
    SN: 'Senegal',
    RS: 'Serbia',
    SC: 'Seychelles',
    SL: 'Sierra Leone',
    SG: 'Singapore',
    SK: 'Slovak Republic',
    SI: 'Slovenia',
    SB: 'Solomon Islands',
    SO: 'Somalia',
    ZA: 'South Africa',
    GS: 'South Georgia And South Sandwich Islands',
    KR: 'South Korea',
    SS: 'South Sudan',
    ES: 'Spain',
    LK: 'Sri Lanka',
    SD: 'Sudan',
    SR: 'Suriname',
    SJ: 'Svalbard And Jan Mayen',
    SZ: 'Swaziland',
    SE: 'Sweden',
    CH: 'Switzerland',
    SY: 'Syria',
    TW: 'Taiwan',
    TJ: 'Tajikistan',
    TZ: 'Tanzania',
    TH: 'Thailand',
    TL: 'Timor-Leste',
    TG: 'Togo',
    TK: 'Tokelau',
    TO: 'Tonga',
    TT: 'Trinidad And Tobago',
    TN: 'Tunisia',
    TR: 'Turkey',
    TM: 'Turkmenistan',
    TC: 'Turks And Caicos Islands',
    TV: 'Tuvalu',
    UG: 'Uganda',
    UA: 'Ukraine',
    AE: 'United Arab Emirates',
    UK: 'United Kingdom',
    US: 'United States',
    UM: 'United States Minor Outlying Islands',
    UY: 'Uruguay',
    UZ: 'Uzbekistan',
    VU: 'Vanuatu',
    VA: 'Vatican City (Holy See)',
    VE: 'Venezuela',
    VN: 'Vietnam',
    VG: 'Virgin Islands (British)',
    VI: 'Virgin Islands (US)',
    WF: 'Wallis And Futuna Islands',
    EH: 'Western Sahara',
    WS: 'Western Samoa',
    YE: 'Yemen',
    YU: 'Yugoslavia',
    ZM: 'Zambia',
    ZW: 'Zimbabwe',
};

// XXX vladislavl: merge with country list and fill zones for other countries
E.timezone = {
    AU: 'Australia/Sydney',
    BA: 'Europe/Sarajevo',
    BE: 'Europe/Brussels',
    BY: 'Europe/Minsk',
    CA: 'Canada/Eastern',
    CN: 'Asia/Shanghai',
    CR: 'America/Costa_Rica',
    DE: 'Europe/Berlin',
    EE: 'Europe/Tallinn',
    ES: 'Europe/Madrid',
    FR: 'Europe/Paris',
    GB: 'Europe/London',
    HK: 'Asia/Hong_Kong',
    IL: 'Israel',
    IN: 'Asia/Colombo',
    KR: 'Asia/Seoul',
    LT: 'Europe/Vilnius',
    MD: 'Europe/Istanbul',
    MT: 'Europe/Malta',
    NL: 'Europe/Amsterdam',
    NO: 'Europe/Oslo',
    PH: 'Asia/Manila',
    PL: 'Poland',
    RU: 'Europe/Moscow',
    SG: 'Asia/Singapore',
    UA: 'Europe/Kiev',
    UK: 'Europe/London',
    US: 'US/Eastern',
    UZ: 'Asia/Tashkent',
};

E.regions = {
    AD: ['Southern Europe'],
    AE: ['Western Asia'],
    AF: ['Southern Asia'],
    AG: ['Caribbean'],
    AI: ['Caribbean'],
    AL: ['South-Eastern Europe'],
    AM: ['Western Asia'],
    AN: ['Caribbean'],
    AO: ['Middle Africa'],
    AP: ['Asia/Pacific'],
    AQ: ['Antarctica'],
    AR: ['South America'],
    AS: ['Polynesia'],
    AT: ['Western Europe'],
    AU: ['Australia and New Zealand'],
    AW: ['Caribbean'],
    AX: ['Scandinavia', 'Northern Europe'],
    AZ: ['Western Asia'],
    BA: ['South-Eastern Europe'],
    BB: ['Caribbean'],
    BD: ['Southern Asia'],
    BE: ['Western Europe'],
    BF: ['Western Africa'],
    BG: ['Eastern Europe'],
    BH: ['Western Asia'],
    BI: ['Eastern Africa'],
    BJ: ['Western Africa'],
    BL: ['Caribbean'],
    BM: ['Northern America'],
    BN: ['South-Eastern Asia'],
    BO: ['South America'],
    BQ: ['Caribbean'],
    BR: ['South America'],
    BS: ['Caribbean'],
    BT: ['Southern Asia'],
    BV: ['Antarctica'],
    BW: ['Southern Africa'],
    BY: ['Eastern Europe'],
    BZ: ['Central America'],
    CA: ['Northern America'],
    CC: ['Australia and New Zealand'],
    CD: ['Middle Africa'],
    CF: ['Middle Africa'],
    CG: ['Middle Africa'],
    CH: ['Western Europe'],
    CI: ['Western Africa'],
    CK: ['Polynesia'],
    CL: ['South America'],
    CM: ['Middle Africa'],
    CN: ['Eastern Asia'],
    CO: ['South America'],
    CR: ['Central America'],
    CU: ['Caribbean'],
    CV: ['Western Africa'],
    CW: ['Caribbean'],
    CX: ['Australia and New Zealand'],
    CY: ['South-Eastern Europe'],
    CZ: ['Eastern Europe'],
    DE: ['Western Europe'],
    DJ: ['Eastern Africa'],
    DK: ['Scandinavia', 'Northern Europe'],
    DM: ['Caribbean'],
    DO: ['Caribbean'],
    DZ: ['Northern Africa'],
    EC: ['South America'],
    EE: ['Eastern Europe'],
    EG: ['Northern Africa'],
    EH: ['Northern Africa'],
    ER: ['Eastern Africa'],
    ES: ['Southern Europe'],
    ET: ['Eastern Africa'],
    EU: ['Western Europe'],
    FI: ['Scandinavia', 'Northern Europe'],
    FJ: ['Melanesia'],
    FK: ['South America'],
    FM: ['Micronesia'],
    FO: ['Scandinavia', 'Northern Europe'],
    FR: ['Western Europe'],
    FX: ['Western Europe'],
    GA: ['Middle Africa'],
    GB: ['Northern Europe'],
    GD: ['Caribbean'],
    GE: ['Western Asia'],
    GF: ['South America'],
    GG: ['Northern Europe'],
    GH: ['Western Africa'],
    GI: ['Southern Europe'],
    GL: ['Scandinavia', 'Northern America'],
    GM: ['Western Africa'],
    GN: ['Western Africa'],
    GP: ['Caribbean'],
    GQ: ['Middle Africa'],
    GR: ['South-Eastern Europe'],
    GS: ['Antarctica'],
    GT: ['Central America'],
    GU: ['Micronesia'],
    GW: ['Western Africa'],
    GY: ['South America'],
    HK: ['Eastern Asia'],
    HM: ['Australia and New Zealand'],
    HN: ['Central America'],
    HR: ['South-Eastern Europe'],
    HT: ['Caribbean'],
    HU: ['Eastern Europe'],
    ID: ['South-Eastern Asia'],
    IE: ['Northern Europe'],
    IL: ['Western Asia'],
    IM: ['Northern Europe'],
    IN: ['Southern Asia'],
    IO: ['Eastern Africa'],
    IQ: ['Western Asia'],
    IR: ['Southern Asia'],
    IS: ['Scandinavia', 'Northern Europe'],
    IT: ['Southern Europe'],
    JE: ['Northern Europe'],
    JM: ['Caribbean'],
    JO: ['Western Asia'],
    JP: ['Eastern Asia'],
    KE: ['Eastern Africa'],
    KG: ['Central Asia'],
    KH: ['South-Eastern Asia'],
    KI: ['Micronesia'],
    KM: ['Eastern Africa'],
    KN: ['Caribbean'],
    KP: ['Eastern Asia'],
    KR: ['Eastern Asia'],
    KW: ['Western Asia'],
    KY: ['Caribbean'],
    KZ: ['Central Asia'],
    LA: ['South-Eastern Asia'],
    LB: ['Western Asia'],
    LC: ['Caribbean'],
    LI: ['Western Europe'],
    LK: ['Southern Asia'],
    LR: ['Western Africa'],
    LS: ['Southern Africa'],
    LT: ['Eastern Europe'],
    LU: ['Western Europe'],
    LV: ['Eastern Europe'],
    LY: ['Northern Africa'],
    MA: ['Northern Africa'],
    MC: ['Western Europe'],
    MD: ['Eastern Europe'],
    ME: ['South-Eastern Europe'],
    MF: ['Caribbean'],
    MG: ['Eastern Africa'],
    MH: ['Micronesia'],
    MK: ['South-Eastern Europe'],
    ML: ['Western Africa'],
    MM: ['South-Eastern Asia'],
    MN: ['Eastern Asia'],
    MO: ['Eastern Asia'],
    MP: ['Micronesia'],
    MQ: ['Caribbean'],
    MR: ['Western Africa'],
    MS: ['Caribbean'],
    MT: ['Southern Europe'],
    MU: ['Eastern Africa'],
    MV: ['Southern Asia'],
    MW: ['Eastern Africa'],
    MX: ['Central America'],
    MY: ['South-Eastern Asia'],
    MZ: ['Eastern Africa'],
    NA: ['Southern Africa'],
    NC: ['Melanesia'],
    NE: ['Western Africa'],
    NF: ['Australia and New Zealand'],
    NG: ['Western Africa'],
    NI: ['Central America'],
    NL: ['Western Europe'],
    NO: ['Scandinavia', 'Northern Europe'],
    NP: ['Southern Asia'],
    NR: ['Micronesia'],
    NU: ['Polynesia'],
    NZ: ['Australia and New Zealand'],
    OM: ['Western Asia'],
    PA: ['Central America'],
    PE: ['South America'],
    PF: ['Polynesia'],
    PG: ['Melanesia'],
    PH: ['South-Eastern Asia'],
    PK: ['Southern Asia'],
    PL: ['Eastern Europe'],
    PM: ['Northern America'],
    PN: ['Polynesia'],
    PR: ['Caribbean'],
    PS: ['Western Asia'],
    PT: ['Southern Europe'],
    PW: ['Micronesia'],
    PY: ['South America'],
    QA: ['Western Asia'],
    RE: ['Eastern Africa'],
    RO: ['Eastern Europe'],
    RS: ['South-Eastern Europe'],
    RU: ['Eastern Europe'],
    RW: ['Eastern Africa'],
    SA: ['Western Asia'],
    SB: ['Melanesia'],
    SC: ['Eastern Africa'],
    SD: ['Northern Africa'],
    SE: ['Scandinavia', 'Northern Europe'],
    SG: ['South-Eastern Asia'],
    SH: ['Western Africa'],
    SI: ['South-Eastern Europe'],
    SJ: ['Scandinavia', 'Northern Europe'],
    SK: ['Eastern Europe'],
    SL: ['Western Africa'],
    SM: ['Southern Europe'],
    SN: ['Western Africa'],
    SO: ['Eastern Africa'],
    SR: ['South America'],
    SS: ['Eastern Africa'],
    ST: ['Middle Africa'],
    SV: ['Central America'],
    SX: ['Caribbean'],
    SY: ['Western Asia'],
    SZ: ['Southern Africa'],
    TC: ['Caribbean'],
    TD: ['Middle Africa'],
    TF: ['Antarctica'],
    TG: ['Western Africa'],
    TH: ['South-Eastern Asia'],
    TJ: ['Central Asia'],
    TK: ['Polynesia'],
    TL: ['South-Eastern Asia'],
    TM: ['Central Asia'],
    TN: ['Northern Africa'],
    TO: ['Polynesia'],
    TP: ['South-Eastern Asia'],
    TR: ['South-Eastern Europe'],
    TT: ['Caribbean'],
    TV: ['Polynesia'],
    TW: ['Eastern Asia'],
    TZ: ['Eastern Africa'],
    UA: ['Eastern Europe'],
    UG: ['Eastern Africa'],
    UK: ['Northern Europe'],
    UM: ['Northern America'],
    US: ['Northern America'],
    UY: ['South America'],
    UZ: ['Central Asia'],
    VA: ['Southern Europe'],
    VC: ['Caribbean'],
    VE: ['South America'],
    VG: ['Caribbean'],
    VI: ['Caribbean'],
    VN: ['South-Eastern Asia'],
    VU: ['Melanesia'],
    WF: ['Polynesia'],
    WS: ['Polynesia'],
    YE: ['Western Asia'],
    YT: ['Eastern Africa'],
    YU: ['South-Eastern Europe'],
    ZA: ['Southern Africa'],
    ZM: ['Eastern Africa'],
    ZW: ['Eastern Africa'],
};
var subregions = {
    'Northern America': ['America'],
    'South America': ['LATAM'],
    'Central America': ['LATAM'],
    Caribbean: ['LATAM'],
    LATAM: ['America'],
    'Eastern Europe': ['Eastern Europe (W/E)'],
    'South-Eastern Europe': ['Eastern Europe (W/E)'],
    'Western Europe': ['Western Europe (W/E)'],
    'Southern Europe': ['Western Europe (W/E)'],
    'Northern Europe': ['Western Europe (W/E)'],
    'Western Europe (W/E)': ['Europe'],
    'Eastern Europe (W/E)': ['Europe'],
    Polynesia: ['Oceania'],
    Melanesia: ['Oceania'],
    Micronesia: ['Oceania'],
    'Australia and New Zealand': ['Oceania'],
    Oceania: ['APAC'],
    'South-Eastern Asia': ['APAC', 'Asia'],
    'Southern Asia': ['APAC', 'Asia'],
    'Eastern Asia': ['APAC', 'Asia'],
    'Central Asia': ['Asia'],
    'Western Asia': ['Asia'],
    'Eastern Africa': ['Africa'],
    'Western Africa': ['Africa'],
    'Southern Africa': ['Africa'],
    'Northern Africa': ['Africa'],
    'Middle Africa': ['Africa'],
};
var extend_regions = function(regions){
    for (var i = 0; i<regions.length; i++)
    {
        (subregions[regions[i]]||[])
        .filter(function(extra){ return !regions.includes(extra); })
        .forEach(function(extra){ regions.push(extra); });
    }
    regions.push('All');
};
for (var country in E.regions)
    extend_regions(E.regions[country]);

E.unallowed_list = {
    SY: 1,
    LB: 1,
    IR: 1,
    IQ: 1,
    DO: 1,
};

E.is_allowed = function(code){
    return E.list[code] && !E.unallowed_list[code];
};

E.lum_easy_pass = {
    AR: 1,
    AT: 1,
    AU: 1,
    BE: 1,
    CA: 1,
    EU: 1,
    FL: 1,
    FR: 1,
    DE: 1,
    GB: 1,
    IE: 1,
    IL: 1,
    IT: 1,
    NL: 1,
    NZ: 1,
    PL: 1,
    PT: 1,
    SG: 1,
    KR: 1,
    SZ: 1,
    SE: 1,
    UK: 1,
    US: 1,
};

E.code2label = function(code){
    code = code.toUpperCase();
    return E.list[code] || code;
};

E.code2timezone = function(code){
    code = code.toUpperCase();
    return E.timezone[code] || code;
};

E.label2code = function(label){
    for (var i in E.list)
    {
        if (E.list[i]===label)
            return i;
    }
    return '';
};

E.mixed2code = function(mixed){
    if (!mixed)
        return;
    if (/^[A-Z]{2}$/.test(mixed))
        return mixed;
    if (mixed.length==2)
        return mixed.toUpperCase();
    if (mixed=='USA')
        return 'US';
    for (var code in E.list)
    {
        if (E.list[code].toLowerCase()==mixed.toLowerCase())
            return code;
    }
    return mixed;
};

E.www2code = function(code){
    return code=='UK' ? 'GB' : code=='uk' ? 'gb' : code; };

E.code2www = function(code){
    return code=='GB' ? 'UK' : code=='gb' ? 'uk' : code; };

return E; }); }());
